# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM package to Github packages

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
      
      - name: Install dependencies
        run: npm ci
  
      - name: Set NPM version
        run: |
            VERSION=${GITHUB_REF#refs/tags/}
            npm version $VERSION --no-git-tag-version --workspaces
  
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Determine NPM tag
        run: ./scripts/determine-npm-tag.sh

      # - name: Publish to public NPM
      #   run: npm publish --workspaces --access public --tag ${{ env.NPM_TAG }}
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm publish --workspaces --access public --tag ${{env.NPM_TAG}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
